/* STK500 constants list, from AVRDUDE */
module.exports.STK_OK              = 0x10;
module.exports.STK_FAILED          = 0x11;  // Not used
module.exports.STK_UNKNOWN         = 0x12;  // Not used
module.exports.STK_NODEVICE        = 0x13;  // Not used
module.exports.STK_INSYNC          = 0x14;  // ' '
module.exports.STK_NOSYNC          = 0x15;  // Not used
module.exports.ADC_CHANNEL_ERROR   = 0x16;  // Not used
module.exports.ADC_MEASURE_OK      = 0x17;  // Not used
module.exports.PWM_CHANNEL_ERROR   = 0x18;  // Not used
module.exports.PWM_ADJUST_OK       = 0x19;  // Not used
module.exports.CRC_EOP             = 0x20;  // 'SPACE'
module.exports.STK_GET_SYNC        = 0x30;  // '0'
module.exports.STK_GET_SIGN_ON     = 0x31;  // '1'
module.exports.STK_SET_PARAMETER   = 0x40;  // '@'
module.exports.STK_GET_PARAMETER   = 0x41;  // 'A'
module.exports.STK_SET_DEVICE      = 0x42;  // 'B'
module.exports.STK_SET_DEVICE_EXT  = 0x45;  // 'E'
module.exports.STK_ENTER_PROGMODE  = 0x50;  // 'P'
module.exports.STK_LEAVE_PROGMODE  = 0x51;  // 'Q'
module.exports.STK_CHIP_ERASE      = 0x52;  // 'R'
module.exports.STK_CHECK_AUTOINC   = 0x53;  // 'S'
module.exports.STK_LOAD_ADDRESS    = 0x55;  // 'U'
module.exports.STK_UNIVERSAL       = 0x56;  // 'V'
module.exports.STK_PROG_FLASH      = 0x60;  // '`'
module.exports.STK_PROG_DATA       = 0x61;  // 'a'
module.exports.STK_PROG_FUSE       = 0x62;  // 'b'
module.exports.STK_PROG_LOCK       = 0x63;  // 'c'
module.exports.STK_PROG_PAGE       = 0x64;  // 'd'
module.exports.STK_PROG_FUSE_EXT   = 0x65;  // 'e'
module.exports.STK_READ_FLASH      = 0x70;  // 'p'
module.exports.STK_READ_DATA       = 0x71;  // 'q'
module.exports.STK_READ_FUSE       = 0x72;  // 'r'
module.exports.STK_READ_LOCK       = 0x73;  // 's'
module.exports.STK_READ_PAGE       = 0x74;  // 't'
module.exports.STK_READ_SIGN       = 0x75;  // 'u'
module.exports.STK_READ_OSCCAL     = 0x76;  // 'v'
module.exports.STK_READ_FUSE_EXT   = 0x77;  // 'w'
module.exports.STK_READ_OSCCAL_EXT = 0x78;  // 'x'